version: "3.9"

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 9812341002
      MYSQL_DATABASE: identity_reconciliation
    # Remove public port exposure for security
    # ports:
    #   - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    # Remove volume mount in prod (use docker image content only)
    # volumes:
    #   - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - mysql
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mysql-data:
